### PR TITLE
fix: missing context script task

### PR DESCRIPTION
**Pull request by abdul99ahad**
Related to camunda-modeler: [#4614](https://github.com/camunda/camunda-modeler/issues/4614)

### Proposed Changes

 

The context of the script task result variable is now available, providing users with property suggestions for the object.Dec-03-2024 16-42-07

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
The code looks OK, and the solution works. There's however one thing about the project which now seems to be confusing.
In the resolver, we call `_resolveIoMappings`. This results in a call to [`parseIoMappings`](https://github.com/bpmn-io/variable-resolver/blob/main/lib/zeebe/util/feelUtility.js#L11). Then we try to [get the expression details](https://github.com/bpmn-io/variable-resolver/blob/main/lib/zeebe/util/feelUtility.js#L161) which now talks about not only iomappings, but also script.
So we move from super specific iomappings talk to general expression-related topics. What I'd rather expect is to start from general `resolveVariables` and only then to move to specifics like iomappings, script expressions, and whatever comes next.
WDYT?

**Comment by abdul99ahad** [comment]
> So we move from super specific iomappings talk to general expression-related topics. What I'd rather expect is to start from general resolveVariables and only then to move to specifics like iomappings, script expressions, and whatever comes next.

Can you check if my refactoring (https://github.com/bpmn-io/variable-resolver/pull/41/commits/ef76957699815ec8e2f4ad78c2553aa25f5c7b0f) is accurate? Since we are only differentiating between `ioMappings` and `scriptVariables` in `getExpressionDetails`, I believe having outer functions specific to io is unnecessary (I might be wrong).

**Review by barmac — APPROVED** [review]
Fantastic!

**Comment by barmac** [comment]
I missed that in the review, but the commit contained premature "closes" clause:
image

It should be "Related to..."

**Pull request merged**
